---
version: 2.1
jobs:
  say_hello:
    docker:
      - image: cimg/base:2022.05
        auth:
          username: gudditi
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: sudo apt update && sudo apt install docker -y
      - run: docker -version
      - run: cat a.txt
  say_goodbye:
    docker:
      - image: cimg/base:2022.05
        auth:
          username: gudditi
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo "Say goodbye to YAML!"
workflows:
  hello_and_goodbye:
    jobs:
      - say_hello
      - say_goodbye
